import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Custom Chenille Patches Manufacturer — Varsity & Fashion | KaKa Patches",
  description: "B2B custom chenille patches with soft raised fuzzy texture for varsity jackets, school apparel, sports teams and fashion brands. Factory-direct production.",
};

const keyFeatures = [
  { title: "Soft Textured Finish", desc: "Chenille patches are made from fuzzy, raised yarn creating a soft, tactile texture that demands attention." },
  { title: "Bold Visual Impact", desc: "The thick, raised yarn creates designs that stand out — perfect for large lettering and mascots." },
  { title: "Iconic Varsity Look", desc: "Chenille patches communicate tradition, achievement and team identity in varsity and sports culture." },
  { title: "Fashion-Forward Appeal", desc: "Beyond athletics, chenille has been embraced by fashion brands and streetwear for its tactile, retro aesthetic." },
];

const faqs = [
  { q: "What are chenille patches made of?", a: "Chenille patches are made from soft, fuzzy yarn (typically acrylic or cotton-blend) stitched onto a felt or fabric backing. The yarn loops create the distinctive soft, raised texture." },
  { q: "What is the best use for chenille?", a: "Chenille patches are best for varsity jackets, letterman jackets, school and team apparel, fashion collections and any application where a bold, textured look is desired." },
  { q: "Are chenille patches durable?", a: "Chenille patches are durable for normal apparel wear. They are best used on jackets, apparel and fashion items rather than high-wear outdoor gear." },
  { q: "Can chenille be combined with embroidery?", a: "Yes. Many designs combine chenille yarn for the main body with embroidered details for finer elements." },
  { q: "How do I get a quote?", a: "Upload your design via our Request a Quote page. We will review and provide a factory-direct production quote." },
];

export default function Page() {
  return (
    <main className="bg-white text-slate-900">
      <section className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(ellipse_60%_50%_at_50%_-10%,rgba(37,99,235,0.2),transparent)]" /><div className="relative mx-auto grid max-w-7xl gap-12 px-6 py-24 md:grid-cols-2 md:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-blue-300">Custom Patch Product</p><h1 className="mt-5 text-4xl font-extrabold leading-tight tracking-tight md:text-6xl">Custom Chenille <span className="text-blue-400">Patches</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Soft raised fuzzy texture for bold visual identity. Best for varsity jackets, school apparel, sports teams, fashion graphics, large letters and mascot designs.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/request-a-quote" className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-7 py-3.5 text-sm font-semibold text-white shadow-lg transition hover:bg-blue-500">Request a Quote →</Link><Link href="/products" className="inline-flex items-center gap-2 rounded-full border border-white/25 px-7 py-3.5 text-sm font-semibold text-white transition hover:bg-white/10">View All Products</Link></div></div><div className="rounded-3xl border border-white/10 bg-white/5 shadow-2xl p-8 md:p-10"><h3 className="text-xl font-bold">Product Highlights</h3><div className="mt-6 space-y-4">{[{l:"Texture",v:"Soft fuzzy raised yarn"},{l:"Best For",v:"Varsity, fashion & large letters"},{l:"Size Range",v:"2″ – 15″+ custom"},{l:"MOQ",v:"100 pcs"},{l:"Lead Time",v:"2–3 weeks"}].map((r)=>(<div key={r.l} className="flex justify-between border-b border-white/10 pb-3 text-sm"><span className="text-slate-400">{r.l}</span><span className="font-medium">{r.v}</span></div>))}</div></div></div></section>

      <section className="py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 md:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Product Overview</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">What Are Custom Chenille Patches?</h2><p className="mt-5 text-lg leading-8 text-slate-600">Custom chenille patches are made by stitching soft, fuzzy yarn onto a felt or fabric backing. The yarn creates a distinctive looped pile surface that is soft to the touch and visually striking. Good for bold visual identity and textured apparel decoration.</p></div><div className="rounded-3xl bg-slate-100 p-8"><h3 className="text-xl font-bold">Ideal Buyer Types</h3><div className="mt-6 grid gap-3">{["School & university suppliers","Varsity jacket manufacturers","Sports teams & clubs","Fashion & streetwear brands","Team apparel companies","Spirit wear & merchandise buyers"].map((i)=>(<div key={i} className="rounded-2xl bg-white px-5 py-4 text-sm font-semibold text-slate-700">{i}</div>))}</div></div></div></section>

      <section className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Best Applications</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Where Chenille Patches Are Used</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Varsity jackets","School apparel","Sports teams","Fashion brands","Letterman jackets","Spirit wear","Large lettering","Mascot designs"].map((i)=>(<div key={i} className="rounded-2xl bg-white px-6 py-5 text-sm font-semibold text-slate-800 shadow-sm">{i}</div>))}</div></div></section>

      <section className="py-24"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Key Features</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Soft Texture, Bold Visual Presence</h2></div><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{keyFeatures.map((f)=>(<div key={f.title} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-blue-100"><svg className="h-5 w-5 text-blue-600" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg></div><h3 className="text-lg font-bold">{f.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{f.desc}</p></div>))}</div></div></section>

      <section className="bg-slate-50 py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 md:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Custom Options</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Customize Your Chenille Patches</h2><Link href="/request-a-quote" className="mt-8 inline-flex items-center gap-2 rounded-full bg-blue-600 px-7 py-3 text-sm font-semibold text-white transition hover:bg-blue-700">Upload Artwork for Quote →</Link></div><div className="grid gap-4 sm:grid-cols-2">{["Custom size up to 15″+","Custom shape and die-cut","Multi-color chenille yarn","Felt or fabric base color","Combined with embroidery detail","Sew-on or iron-on backing","Individual or bulk packaging","Sample and production support"].map((i)=>(<div key={i} className="rounded-2xl border border-slate-200 bg-white px-5 py-4 text-sm font-semibold text-slate-700">{i}</div>))}</div></div></section>

      <section className="bg-slate-950 py-24 text-white"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-300">Backing Options</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Choose the Right Attachment</h2></div><div className="mt-14 grid gap-6 md:grid-cols-3">{[{t:"Sew-on",d:"The standard for chenille — permanent attachment for jackets and apparel."},{t:"Iron-on",d:"Heat-applied for faster production on fabric items."},{t:"Adhesive",d:"Peel-and-stick for promotional items and fashion accessories."}].map((b)=>(<div key={b.t} className="rounded-3xl border border-white/10 bg-white/5 p-7"><h3 className="text-lg font-bold">{b.t}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{b.d}</p></div>))}</div></div></section>

      <section className="py-24"><div className="mx-auto max-w-3xl px-6"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">FAQ</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Frequently Asked Questions</h2></div><div className="mt-14 divide-y divide-slate-200">{faqs.map((item)=>(<details key={item.q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-left text-base font-semibold text-slate-900 hover:text-blue-600">{item.q}<span className="text-slate-400 transition group-open:rotate-45">+</span></summary><p className="mt-4 pr-12 text-sm leading-7 text-slate-600">{item.a}</p></details>))}</div></div></section>

      <section className="bg-blue-600 py-20 text-white"><div className="mx-auto max-w-4xl px-6 text-center"><h2 className="text-3xl font-bold md:text-4xl">Need Soft Textured Chenille Patches?</h2><div className="mt-10"><Link href="/request-a-quote" className="inline-flex items-center gap-2 rounded-full bg-white px-8 py-3.5 text-sm font-semibold text-blue-700 shadow-lg transition hover:bg-blue-50">Request a Quote →</Link></div></div></section>
    </main>
  );
}
