import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Custom Patches for Uniforms — Workwear & Staff Badges | KaKa Patches",
  description: "Durable custom patches for workwear, staff uniforms, school uniforms, security uniforms and organization badges. B2B bulk production.",
};

export default function Page() {
  return (
    <main className="bg-white text-slate-900">
      <section className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(ellipse_60%_50%_at_50%_-10%,rgba(37,99,235,0.25),transparent)]" /><div className="relative mx-auto max-w-7xl px-6 py-24 md:py-32"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-blue-300">Application</p><h1 className="mt-5 max-w-4xl text-4xl font-extrabold leading-tight tracking-tight md:text-6xl">Custom Patches for <span className="text-blue-400">Uniforms</span></h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Durable custom patches for workwear, staff uniforms, school uniforms, security uniforms, service apparel and organization badges. Designed for daily-use programs.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/request-a-quote" className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-7 py-3.5 text-sm font-semibold text-white shadow-lg transition hover:bg-blue-500">Request a Quote →</Link><Link href="/applications" className="inline-flex items-center gap-2 rounded-full border border-white/25 px-7 py-3.5 text-sm font-semibold text-white transition hover:bg-white/10">All Applications</Link></div></div></section>
      <section className="py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 md:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Application Overview</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">For Daily-Use Uniforms</h2><p className="mt-5 text-lg leading-8 text-slate-600">Uniform patches must be durable, consistent across large quantities and able to withstand repeated washing — often in industrial laundry conditions. KaKa Patches supports uniform suppliers with patches built for professional daily use.</p></div><div className="rounded-3xl bg-slate-100 p-8"><h3 className="text-xl font-bold">Common Products</h3><div className="mt-6 grid gap-3">{["Workwear & industrial uniforms","Staff & service uniforms","School uniforms","Security uniforms","Hospitality uniforms","Organization badges"].map((i)=>(<div key={i} className="rounded-2xl bg-white px-5 py-4 text-sm font-semibold text-slate-700">{i}</div>))}</div></div></div></section>
      <section className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Recommended Patch Types</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Patch Types for Uniforms</h2></div><div className="mt-14 grid gap-6 md:grid-cols-3">{[{t:"Embroidered Patches",d:"The standard for durable uniform identity — withstands industrial laundering.",h:"/products/custom-embroidered-patches"},{t:"Woven Patches",d:"Best for detailed badges and text-heavy uniform insignia.",h:"/products/custom-woven-patches"},{t:"PVC Patches",d:"Ideal for removable patches and outdoor workwear.",h:"/products/custom-pvc-patches"}].map((p)=>(<Link key={p.h} href={p.h} className="group rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg"><h3 className="text-lg font-bold">{p.t}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{p.d}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-blue-600">Learn More →</span></Link>))}</div></div></section>
      <section className="bg-blue-600 py-20 text-white"><div className="mx-auto max-w-4xl px-6 text-center"><h2 className="text-3xl font-bold md:text-4xl">Need Durable Uniform Patches?</h2><div className="mt-10"><Link href="/request-a-quote" className="inline-flex items-center gap-2 rounded-full bg-white px-8 py-3.5 text-sm font-semibold text-blue-700 shadow-lg transition hover:bg-blue-50">Request a Quote →</Link></div></div></section>
    </main>
  );
}
