import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Custom Patches for Clothing Brands — Apparel Solutions | KaKa Patches",
  description: "Custom patches for apparel brands, streetwear labels, fashion collections, jackets, hats, bags and brand merchandise. B2B factory-direct production.",
};

export default function Page() {
  return (
    <main className="bg-white text-slate-900">
      <section className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(ellipse_60%_50%_at_50%_-10%,rgba(37,99,235,0.25),transparent)]" /><div className="relative mx-auto max-w-7xl px-6 py-24 md:py-32"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-blue-300">Application</p><h1 className="mt-5 max-w-4xl text-4xl font-extrabold leading-tight tracking-tight md:text-6xl">Custom Patches for <span className="text-blue-400">Clothing Brands</span></h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Custom patches for apparel brands, streetwear labels, fashion collections, jackets, hats, bags and brand merchandise. Add signature branding that customers see and remember.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/request-a-quote" className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-7 py-3.5 text-sm font-semibold text-white shadow-lg transition hover:bg-blue-500">Request a Quote →</Link><Link href="/applications" className="inline-flex items-center gap-2 rounded-full border border-white/25 px-7 py-3.5 text-sm font-semibold text-white transition hover:bg-white/10">All Applications</Link></div></div></section>
      <section className="py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 md:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Application Overview</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">For Apparel Branding</h2><p className="mt-5 text-lg leading-8 text-slate-600">Clothing brands use custom patches to add distinctive branding. Whether you are a streetwear label adding logo patches to jackets or a fashion brand creating branded labels — the right patch type elevates brand presentation. Patches offer a tactile, premium alternative to screen printing or woven labels.</p></div><div className="rounded-3xl bg-slate-100 p-8"><h3 className="text-xl font-bold">Common Products</h3><div className="mt-6 grid gap-3">{["Jackets & outerwear","Caps & headwear","Bags & backpacks","Denim & jeans","T-shirts & hoodies","Clothing labels & tags"].map((i)=>(<div key={i} className="rounded-2xl bg-white px-5 py-4 text-sm font-semibold text-slate-700">{i}</div>))}</div></div></div></section>
      <section className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Recommended Patch Types</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">All Four Types for Apparel Brands</h2></div><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{[{t:"Woven Patches",d:"Fine details and small logos on labels and premium tags.",h:"/products/custom-woven-patches"},{t:"Embroidered Patches",d:"Classic brand texture on jackets, caps and accessories.",h:"/products/custom-embroidered-patches"},{t:"PVC Patches",d:"Bold streetwear accessories — waterproof and flexible.",h:"/products/custom-pvc-patches"},{t:"Chenille Patches",d:"Fashion graphics and varsity-style collections with soft texture.",h:"/products/custom-chenille-patches"}].map((p)=>(<Link key={p.h} href={p.h} className="group rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg"><h3 className="text-lg font-bold">{p.t}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{p.d}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-blue-600">Learn More →</span></Link>))}</div></div></section>
      <section className="bg-blue-600 py-20 text-white"><div className="mx-auto max-w-4xl px-6 text-center"><h2 className="text-3xl font-bold md:text-4xl">Ready to Add Custom Patches to Your Brand?</h2><div className="mt-10"><Link href="/request-a-quote" className="inline-flex items-center gap-2 rounded-full bg-white px-8 py-3.5 text-sm font-semibold text-blue-700 shadow-lg transition hover:bg-blue-50">Request a Quote →</Link></div></div></section>
    </main>
  );
}
