import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Custom Embroidered Patches Manufacturer | KaKa Patches",
  description: "B2B custom embroidered patches with classic raised stitching for uniforms, apparel brands, sports teams and promotional products. Factory-direct production with artwork support.",
};

const keyFeatures = [
  { title: "Classic Stitched Texture", desc: "Raised embroidery threads create a traditional, premium look recognized across industries worldwide." },
  { title: "Strong Durability", desc: "Proven on uniforms, jackets, hats and bags — embroidered patches withstand repeated washing and heavy use." },
  { title: "Widest Application Range", desc: "From corporate uniforms to sports merchandise to fashion collections — the most versatile patch type." },
  { title: "Bulk Order Optimized", desc: "Scalable production from 100 to 100,000+ pieces with consistent thread quality and color accuracy." },
];

const customizationOptions = ["Custom patch size and shape", "Thread color matching (PMS)", "Merrowed or heat-cut border", "Sew-on, iron-on, Velcro or adhesive backing", "Individual or bulk packaging", "Logo, badge, mascot, text or emblem designs", "Sample and bulk production support", "Multi-layer and 3D embroidery options"];

const faqs = [
  { q: "What are custom embroidered patches best for?", a: "Embroidered patches are best for classic logo patches, uniforms, jackets, hats, clubs, teams, brand merchandise and promotional products where a raised stitched texture and traditional appearance are desired." },
  { q: "Can embroidered patches show very small text?", a: "Embroidered patches can reproduce most logo details well, but very small text (under ~5mm) may not be as sharp as woven patches. Our team can advise on the best patch type for your design." },
  { q: "What backing options are available?", a: "Sew-on, iron-on, Velcro and adhesive backing are all available. Sew-on is the most durable; iron-on is convenient for fabric production; Velcro is best for removable patches; adhesive works for temporary applications." },
  { q: "Can I order custom sizes and shapes?", a: "Yes. We support fully custom sizes from 1″ to 15″+ and any shape — standard geometric, contour-cut or fully custom die-cut." },
  { q: "How do I get a quote?", a: "Upload your artwork through our Request a Quote page and provide patch size, quantity, backing option and delivery requirements. We respond with a detailed quote — typically within 1 business day." },
];

export default function CustomEmbroideredPatchesPage() {
  return (
    <main className="bg-white text-slate-900">
      <section className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(ellipse_60%_50%_at_50%_-10%,rgba(37,99,235,0.25),transparent)]" /><div className="relative mx-auto grid max-w-7xl gap-12 px-6 py-24 md:grid-cols-2 md:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-blue-300">Custom Patch Product</p><h1 className="mt-5 text-4xl font-extrabold leading-tight tracking-tight md:text-6xl md:leading-[1.1]">Custom Embroidered <span className="text-blue-400">Patches</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Classic stitched patches with raised embroidery texture. Best for uniforms, jackets, workwear, clubs, brand patches and promotional products. Factory-direct production with full customization support.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/request-a-quote" className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-7 py-3.5 text-sm font-semibold text-white shadow-lg transition hover:bg-blue-500">Request a Quote <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" /></svg></Link><Link href="/products" className="inline-flex items-center gap-2 rounded-full border border-white/25 px-7 py-3.5 text-sm font-semibold text-white transition hover:bg-white/10">View All Products</Link></div></div><div className="rounded-3xl border border-white/10 bg-white/5 p-1 shadow-2xl"><div className="rounded-[22px] bg-gradient-to-br from-slate-900 to-slate-950 p-8 md:p-10"><div className="mb-8 flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-600 text-sm font-bold">E</div><div><p className="text-sm font-semibold">Embroidered Patches</p><p className="text-xs text-slate-400">Classic Stitched Production</p></div></div><div className="space-y-5">{[{ label: "Best For", value: "Uniforms, clubs & merchandise" },{ label: "Texture", value: "Raised stitched thread" },{ label: "Versatility", value: "Widest application range" },{ label: "Typical MOQ", value: "100 pcs" },{ label: "Lead Time", value: "2–3 weeks standard" }].map((row) => (<div key={row.label} className="flex items-center justify-between border-b border-white/10 pb-4 text-sm"><span className="text-slate-400">{row.label}</span><span className="font-medium">{row.value}</span></div>))}</div></div></div></div></section>

      <section className="py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 md:grid-cols-2 md:items-start"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Product Overview</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">What Are Custom Embroidered Patches?</h2><p className="mt-5 text-lg leading-8 text-slate-600">Custom embroidered patches are made by stitching thread onto a fabric base to create logos, badges, text and decorative designs. The raised thread texture creates a classic, premium look recognized across industries worldwide.</p><p className="mt-5 text-lg leading-8 text-slate-600">Compared with printed labels, embroidered patches offer proven durability, a traditional aesthetic and the widest range of applications — from corporate uniforms to sports merchandise to fashion branding. Good for medium-complexity logos and traditional patch designs.</p></div><div className="rounded-3xl bg-slate-100 p-8"><h3 className="text-xl font-bold">Ideal Buyer Types</h3><div className="mt-6 grid gap-3">{["Apparel & fashion brands","Uniform suppliers","Sports teams & clubs","Schools & universities","Promotional product distributors","Corporate branding & events"].map((item) => (<div key={item} className="rounded-2xl bg-white px-5 py-4 text-sm font-semibold text-slate-700">{item}</div>))}</div></div></div></section>

      <section className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Best Applications</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Where Custom Embroidered Patches Are Used</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Uniforms & workwear","Sports teams & clubs","Apparel & fashion brands","Schools & universities","Promotional products","Event merchandise","Caps, hats & bags","Brand merchandise"].map((item) => (<div key={item} className="rounded-2xl bg-white px-6 py-5 text-sm font-semibold text-slate-800 shadow-sm">{item}</div>))}</div></div></section>

      <section className="py-24"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Key Features</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">The Most Versatile and Widely Used Patch Type</h2></div><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{keyFeatures.map((f) => (<div key={f.title} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:border-blue-200 hover:shadow-md"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-blue-100"><svg className="h-5 w-5 text-blue-600" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg></div><h3 className="text-lg font-bold">{f.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{f.desc}</p></div>))}</div></div></section>

      <section className="bg-slate-50 py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 md:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Custom Options</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Customize Every Detail</h2><p className="mt-5 text-lg leading-8 text-slate-600">Send your artwork, logo, sketch or design reference and our team will help review the details before production.</p><Link href="/request-a-quote" className="mt-8 inline-flex items-center gap-2 rounded-full bg-blue-600 px-7 py-3 text-sm font-semibold text-white transition hover:bg-blue-700">Upload Artwork for Quote <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" /></svg></Link></div><div className="grid gap-4 sm:grid-cols-2">{customizationOptions.map((item) => (<div key={item} className="rounded-2xl border border-slate-200 bg-white px-5 py-4 text-sm font-semibold text-slate-700">{item}</div>))}</div></div></section>

      <section className="bg-slate-950 py-24 text-white"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-300">Backing Options</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Choose the Right Backing</h2></div><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{[{ title: "Sew-on Backing", desc: "The standard for permanent attachment on uniforms and products needing maximum durability." },{ title: "Iron-on Backing", desc: "Heat-activated adhesive for fast application on fabric." },{ title: "Velcro Backing", desc: "Hook-and-loop for removable patches on bags and interchangeable badge systems." },{ title: "Adhesive Backing", desc: "Peel-and-stick for temporary use and event merchandise." }].map((b) => (<div key={b.title} className="rounded-3xl border border-white/10 bg-white/5 p-7 transition hover:border-blue-500/30"><h3 className="text-lg font-bold">{b.title}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{b.desc}</p></div>))}</div></div></section>

      <section className="py-24"><div className="mx-auto max-w-3xl px-6"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">FAQ</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Frequently Asked Questions</h2></div><div className="mt-14 divide-y divide-slate-200">{faqs.map((item) => (<details key={item.q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-left text-base font-semibold text-slate-900 hover:text-blue-600">{item.q}<span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-slate-300 text-slate-400 transition group-open:rotate-45">+</span></summary><p className="mt-4 pr-12 text-sm leading-7 text-slate-600">{item.a}</p></details>))}</div></div></section>

      <section className="bg-blue-600 py-20 text-white"><div className="mx-auto max-w-4xl px-6 text-center"><h2 className="text-3xl font-bold md:text-4xl">Need Custom Embroidered Patches?</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-blue-50">Upload your artwork and tell us your requirements. We will prepare a factory-direct quote — typically within 1 business day.</p><div className="mt-10"><Link href="/request-a-quote" className="inline-flex items-center gap-2 rounded-full bg-white px-8 py-3.5 text-sm font-semibold text-blue-700 shadow-lg transition hover:bg-blue-50">Request a Quote <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" /></svg></Link></div></div></section>
    </main>
  );
}
