import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About KaKa Patches | Custom Patch Manufacturer",
  description: "KaKa Patches is a B2B custom patch manufacturer supporting embroidered, woven, PVC and chenille patches for apparel brands, sports teams, uniform suppliers and promotional companies.",
};

export default function Page() {
  return (
    <main className="bg-white text-slate-900">
      <section className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(ellipse_60%_50%_at_50%_-10%,rgba(37,99,235,0.25),transparent)]" /><div className="relative mx-auto max-w-7xl px-6 py-24 md:py-32"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-blue-300">About Us</p><h1 className="mt-5 max-w-3xl text-4xl font-extrabold leading-tight tracking-tight md:text-6xl">About <span className="text-blue-400">KaKa Patches</span></h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">KaKa Patches is a B2B custom patch manufacturer helping clothing brands, sports teams, uniform suppliers, clubs, events and promotional buyers create embroidered, woven, PVC and chenille patches. Factory-direct production with artwork support and flexible customization.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/request-a-quote" className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-7 py-3.5 text-sm font-semibold text-white shadow-lg transition hover:bg-blue-500">Request a Quote →</Link><Link href="/products" className="inline-flex items-center gap-2 rounded-full border border-white/25 px-7 py-3.5 text-sm font-semibold text-white transition hover:bg-white/10">View Products</Link></div></div></section>

      <section className="py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 md:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Who We Are</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Custom Patch Manufacturing for B2B Buyers</h2><p className="mt-5 text-lg leading-8 text-slate-600">KaKa Patches focuses on custom patch production for business buyers who need reliable communication, flexible customization and repeatable quality. We manufacture four core patch types — embroidered, woven, PVC and chenille — for apparel brands, sports teams, uniform suppliers, event organizers and promotional product companies.</p></div><div className="rounded-3xl bg-slate-100 p-8"><h3 className="text-xl font-bold">We Support</h3><div className="mt-6 grid gap-3">{["Apparel brands","Sports teams","Uniform suppliers","Event organizers","Promotional product companies","Clubs & organizations"].map((i)=>(<div key={i} className="rounded-2xl bg-white px-5 py-4 text-sm font-semibold text-slate-700">{i}</div>))}</div></div></div></section>

      <section className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">What We Do</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">End-to-End Patch Production Support</h2></div><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{[{t:"Artwork Review",d:"Upload logos, sketches or reference images. Our team reviews every file for patch suitability."},{t:"Patch Type Recommendation",d:"We help choose between embroidered, woven, PVC and chenille."},{t:"Custom Production",d:"Customize size, shape, colors, border, backing and packaging."},{t:"Bulk Order Support",d:"Samples, bulk orders, repeat orders and project-based purchasing."}].map((c)=>(<div key={c.t} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h3 className="text-lg font-bold">{c.t}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{c.d}</p></div>))}</div></div></section>

      <section className="py-24"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">By the Numbers</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Built for B2B Patch Production</h2></div><div className="mt-14 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{[{v:"4",l:"Patch types supported"},{v:"100+",l:"Pcs sample-friendly orders"},{v:"2–3",l:"Weeks typical bulk production"},{v:"Custom",l:"Size, shape, backing & border"}].map((m)=>(<div key={m.l} className="rounded-3xl border border-slate-200 bg-white p-7 text-center shadow-sm"><p className="text-4xl font-extrabold text-blue-600">{m.v}</p><p className="mt-3 text-sm font-medium text-slate-600">{m.l}</p></div>))}</div></div></section>

      <section className="bg-blue-600 py-20 text-white"><div className="mx-auto max-w-4xl px-6 text-center"><h2 className="text-3xl font-bold md:text-4xl">Ready to Work with a Custom Patch Manufacturer?</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-blue-50">Upload your artwork and tell us your requirements. We'll prepare a factory-direct quote.</p><div className="mt-10"><Link href="/request-a-quote" className="inline-flex items-center gap-2 rounded-full bg-white px-8 py-3.5 text-sm font-semibold text-blue-700 shadow-lg transition hover:bg-blue-50">Request a Quote →</Link></div></div></section>
    </main>
  );
}
