/**
 * Production Database Backup Script
 * Creates a logical SQL dump of the quote_requests table.
 * Stores output OUTSIDE the repository.
 *
 * Usage: node scripts/backup-db.mjs
 */
import postgres from "postgres";
import { createHash } from "crypto";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { homedir } from "os";
import { join } from "path";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error("DATABASE_URL not set");
  process.exit(1);
}

const BACKUP_DIR = join(homedir(), "kaka-backups");
if (!existsSync(BACKUP_DIR)) mkdirSync(BACKUP_DIR, { recursive: true });

const TIMESTAMP = new Date().toISOString().replace(/[:.]/g, "-").replace("T", "T");
const BACKUP_FILE = join(BACKUP_DIR, `kaka-prod-backup-${TIMESTAMP}.sql`);

async function main() {
  const sql = postgres(DATABASE_URL, { max: 1 });

  try {
    console.log("Connecting to Neon Postgres for backup...");

    // Get table schema
    const columns = await sql.unsafe(`
      SELECT column_name, data_type, is_nullable, column_default
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'quote_requests'
      ORDER BY ordinal_position
    `);

    // Export all rows
    const rows = await sql.unsafe(`SELECT * FROM quote_requests ORDER BY created_at`);

    console.log(`Exported ${rows.length} rows from quote_requests`);

    // Build SQL dump
    let dump = `-- KaKa Patches Production Backup
-- Database: Neon Serverless Postgres
-- Timestamp: ${new Date().toISOString()}
-- Rows: ${rows.length}
-- Table: quote_requests
-- Generated by: scripts/backup-db.mjs
--

`;

    // Schema
    dump += `-- Schema for quote_requests (${columns.length} columns)
CREATE TABLE IF NOT EXISTS quote_requests (\n`;
    const colDefs = [];
    for (const c of columns) {
      let def = `  ${c.column_name} ${c.data_type}`;
      if (c.is_nullable === 'NO') def += ' NOT NULL';
      if (c.column_default && c.column_default !== 'none') def += ` DEFAULT ${c.column_default}`;
      colDefs.push(def);
    }
    dump += colDefs.join(",\n");
    dump += `\n);

`;

    // Data as INSERT statements (batch of 5 rows per INSERT for readability)
    const colNames = columns.map(c => c.column_name);
    for (let i = 0; i < rows.length; i++) {
      const row = rows[i];
      const vals = colNames.map(col => {
        const v = row[col];
        if (v === null || v === undefined) return 'NULL';
        if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE';
        if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
        // Escape single quotes
        const escaped = String(v).replace(/'/g, "''");
        return `'${escaped}'`;
      });
      dump += `INSERT INTO quote_requests (${colNames.join(", ")}) VALUES (${vals.join(", ")});\n`;
    }

    dump += `\n-- End of backup. ${rows.length} rows exported.
`;

    // Write backup file
    writeFileSync(BACKUP_FILE, dump, "utf-8");

    // Generate checksum
    const content = dump;
    const sha256 = createHash("sha256").update(content).digest("hex");
    writeFileSync(BACKUP_FILE + ".sha256", sha256, "utf-8");

    // Count by category (sanitized)
    const testCount = rows.filter(r => (r.email || "").includes("@example.com") || (r.email || "").includes("test")).length;
    const prodCount = rows.length - testCount;
    const artworkCount = rows.filter(r => r.artwork_url).length;

    console.log(`\n=== BACKUP COMPLETE ===`);
    console.log(`File: ${BACKUP_FILE}`);
    console.log(`Size: ${Buffer.byteLength(content, 'utf8')} bytes`);
    console.log(`SHA256: ${sha256}`);
    console.log(`Rows: ${rows.length} (${prodCount} production, ${testCount} test)`);
    console.log(`Artwork references: ${artworkCount}`);
    console.log(`Columns: ${columns.length}`);
    console.log(`Backup dir: ${BACKUP_DIR}`);
    console.log(`\nRestore command: psql <DATABASE_URL> < ${BACKUP_FILE}`);
  } finally {
    await sql.end();
  }
}

main().catch(e => { console.error(e); process.exit(1); });
