import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Custom Woven Patches Manufacturer — Fine Detail Production | KaKa Patches",
  description: "B2B custom woven patches with smooth surface and fine detail for clothing labels, fashion brands and premium apparel. Factory-direct production with artwork support.",
};

const keyFeatures = [
  { title: "Fine Detail Reproduction", desc: "Woven patches use thinner threads and a tighter weave, making them the best choice for small text, intricate logos and clean lines." },
  { title: "Smooth Flat Finish", desc: "Unlike raised embroidery, woven patches have a flat surface ideal for clothing labels, premium brand tags and detailed badges." },
  { title: "Premium Appearance", desc: "The clean, sharp finish is favored by fashion brands and apparel labels wanting a refined brand presentation." },
  { title: "Flexible Customization", desc: "Custom size, shape, color matching, border style and backing options available for your B2B requirements." },
];

const faqs = [
  { q: "What is the difference between woven and embroidered patches?", a: "Woven patches use thinner threads in a tighter weave, creating a smooth flat surface ideal for fine details and small text. Embroidered patches use thicker threads creating a raised, textured surface." },
  { q: "Can woven patches show very small text?", a: "Yes — this is the main advantage. Small text and intricate artwork that may not reproduce well in embroidery can be produced cleanly with woven patch production." },
  { q: "Are woven patches durable?", a: "Yes. Woven patches are highly durable and maintain their appearance through washing and regular wear." },
  { q: "What backing options are available?", a: "Sew-on, iron-on, Velcro and adhesive backing are all available for woven patches." },
  { q: "How do I get a quote?", a: "Upload your artwork through our Request a Quote page and provide patch size, quantity, backing option and delivery requirements." },
];

export default function Page() {
  return (
    <main className="bg-white text-slate-900">
      <section className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(ellipse_60%_50%_at_50%_-10%,rgba(37,99,235,0.2),transparent)]" /><div className="relative mx-auto grid max-w-7xl gap-12 px-6 py-24 md:grid-cols-2 md:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-blue-300">Custom Patch Product</p><h1 className="mt-5 text-4xl font-extrabold leading-tight tracking-tight md:text-6xl">Custom Woven <span className="text-blue-400">Patches</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Smooth woven surface with fine detail capability. Best for small text, clean logo lines, clothing labels, fashion brands and premium apparel.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/request-a-quote" className="inline-flex items-center gap-2 rounded-full bg-blue-600 px-7 py-3.5 text-sm font-semibold text-white shadow-lg transition hover:bg-blue-500">Request a Quote →</Link><Link href="/products" className="inline-flex items-center gap-2 rounded-full border border-white/25 px-7 py-3.5 text-sm font-semibold text-white transition hover:bg-white/10">View All Products</Link></div></div><div className="rounded-3xl border border-white/10 bg-white/5 shadow-2xl p-8 md:p-10"><h3 className="text-xl font-bold">Product Highlights</h3><div className="mt-6 space-y-4">{[{ l:"Texture", v:"Smooth flat finish" },{ l:"Detail Level", v:"Excellent — best in class" },{ l:"Best For", v:"Fine detail & small text" },{ l:"MOQ", v:"100 pcs" },{ l:"Lead Time", v:"2–3 weeks" }].map((r)=>(<div key={r.l} className="flex justify-between border-b border-white/10 pb-3 text-sm"><span className="text-slate-400">{r.l}</span><span className="font-medium">{r.v}</span></div>))}</div></div></div></section>

      <section className="py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 md:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Product Overview</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">What Are Custom Woven Patches?</h2><p className="mt-5 text-lg leading-8 text-slate-600">Custom woven patches are made by weaving thin polyester threads together on a fabric base. Unlike embroidered patches, woven patches produce a flat, smooth surface with much finer detail capability — making them the preferred choice for small text and intricate artwork. Good for detailed artwork that may not work well with embroidery.</p></div><div className="rounded-3xl bg-slate-100 p-8"><h3 className="text-xl font-bold">Ideal Buyer Types</h3><div className="mt-6 grid gap-3">{["Clothing & fashion brands","Premium apparel labels","Corporate merchandise buyers","Detailed logo projects","Promotional product companies","Uniform suppliers"].map((i)=>(<div key={i} className="rounded-2xl bg-white px-5 py-4 text-sm font-semibold text-slate-700">{i}</div>))}</div></div></div></section>

      <section className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Best Applications</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Where Woven Patches Are Used</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Clothing labels & brand tags","Fashion brands","Premium apparel","Detailed logo patches","Corporate merchandise","Promotional products","Accessory branding","Fine-text designs"].map((i)=>(<div key={i} className="rounded-2xl bg-white px-6 py-5 text-sm font-semibold text-slate-800 shadow-sm">{i}</div>))}</div></div></section>

      <section className="py-24"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Key Features</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Best for Detailed Logos and Small Text</h2></div><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{keyFeatures.map((f)=>(<div key={f.title} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-blue-100"><svg className="h-5 w-5 text-blue-600" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg></div><h3 className="text-lg font-bold">{f.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{f.desc}</p></div>))}</div></div></section>

      <section className="bg-slate-50 py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 md:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">Custom Options</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Customize Every Detail</h2><Link href="/request-a-quote" className="mt-8 inline-flex items-center gap-2 rounded-full bg-blue-600 px-7 py-3 text-sm font-semibold text-white transition hover:bg-blue-700">Upload Artwork for Quote →</Link></div><div className="grid gap-4 sm:grid-cols-2">{["Custom patch size and shape","PMS color matching","Merrowed or heat-cut border","Sew-on, iron-on or adhesive backing","Individual or bulk packaging","Logo, badge, label or emblem designs","Sample and bulk production support","No minimum on detail complexity"].map((i)=>(<div key={i} className="rounded-2xl border border-slate-200 bg-white px-5 py-4 text-sm font-semibold text-slate-700">{i}</div>))}</div></div></section>

      <section className="bg-slate-950 py-24 text-white"><div className="mx-auto max-w-7xl px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-300">Backing Options</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Choose the Right Backing</h2></div><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{[{t:"Sew-on",d:"Permanent attachment for garments and products requiring maximum durability."},{t:"Iron-on",d:"Heat-applied for fast production on fabric items."},{t:"Velcro",d:"Removable attachment for interchangeable patches."},{t:"Adhesive",d:"Peel-and-stick for promotional and temporary applications."}].map((b)=>(<div key={b.t} className="rounded-3xl border border-white/10 bg-white/5 p-7"><h3 className="text-lg font-bold">{b.t}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{b.d}</p></div>))}</div></div></section>

      <section className="py-24"><div className="mx-auto max-w-3xl px-6"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-600">FAQ</p><h2 className="mt-4 text-3xl font-bold md:text-4xl">Frequently Asked Questions</h2></div><div className="mt-14 divide-y divide-slate-200">{faqs.map((item)=>(<details key={item.q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-left text-base font-semibold text-slate-900 hover:text-blue-600">{item.q}<span className="text-slate-400 transition group-open:rotate-45">+</span></summary><p className="mt-4 pr-12 text-sm leading-7 text-slate-600">{item.a}</p></details>))}</div></div></section>

      <section className="bg-blue-600 py-20 text-white"><div className="mx-auto max-w-4xl px-6 text-center"><h2 className="text-3xl font-bold md:text-4xl">Need Fine-Detail Woven Patches?</h2><div className="mt-10"><Link href="/request-a-quote" className="inline-flex items-center gap-2 rounded-full bg-white px-8 py-3.5 text-sm font-semibold text-blue-700 shadow-lg transition hover:bg-blue-50">Request a Quote →</Link></div></div></section>
    </main>
  );
}
